# Generated by Django 6.0.7 on 2026-07-17 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_businesshours_closedday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='queue_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Waiting', 'Waiting'), ('Serving', 'Serving'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
    ]
