# Generated by Django 6.0.7 on 2026-07-11 13:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrate_legacy_accounts(apps, schema_editor):
    LegacyAccount = apps.get_model("accounts", "User")
    AuthUser = apps.get_model("auth", "User")
    db_alias = schema_editor.connection.alias

    for legacy_user in LegacyAccount.objects.using(db_alias).select_related("role"):
        if AuthUser.objects.using(db_alias).filter(pk=legacy_user.pk).exists():
            continue

        name_parts = (legacy_user.full_name or "").split(" ", 1)
        first_name = name_parts[0] if name_parts else ""
        last_name = name_parts[1] if len(name_parts) > 1 else ""
        role_name = (getattr(legacy_user.role, "role_name", "") or "").lower()

        auth_user = AuthUser(
            id=legacy_user.pk,
            username=f"legacy_{legacy_user.pk}",
            first_name=first_name,
            last_name=last_name,
            email=legacy_user.email,
            password="!",
            is_staff=role_name in {"admin", "staff", "administrator"},
            is_superuser=role_name in {"admin", "administrator"},
            is_active=True,
        )
        auth_user.save(using=db_alias, force_insert=True)

    if schema_editor.connection.vendor == 'postgresql':
        with schema_editor.connection.cursor() as cursor:
            cursor.execute(
                "SELECT setval(pg_get_serial_sequence('auth_user', 'id'), COALESCE(MAX(id), 1), MAX(id) IS NOT NULL) FROM auth_user;"
            )


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(migrate_legacy_accounts, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='staff',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
